### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by JuniorMiqueletti** [db1group/default-architecture-vue#1]
Hi guys, How're you doing?
There's a text written on Readme about the license,
but there isn't a LICENSE file...
What about adding this file? :)

An easy way is to go to the root of the repository, click on "Create new file" > Write "LICENSE" to new File and then click in "Choose a license template" that appears on the right side.. ok? :)

**Comment by julianobailao** [comment]
Hi, thanks for the suggestion.

I will do this.

**Comment by julianobailao** [comment]
Created: https://github.com/db1group/default-architecture-vue/pull/2

**Comment by JuniorMiqueletti** [comment]
Welcome :D
